apiVersion: v1
kind: Service
metadata:
  name: fitlyfe-backend
  namespace: default
spec:
  selector:
    app: fitlyfe-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer # Or ClusterIP/NodePort depending on K3s setup
